-- Migration number: 0002 	 2026-10-09T07:46:47.869Z

ALTER TABLE projects ADD COLUMN role TEXT NOT NULL DEFAULT '';

ALTER TABLE projects ADD COLUMN services TEXT NOT NULL DEFAULT '[]';

ALTER TABLE projects ADD COLUMN software TEXT NOT NULL DEFAULT '[]';

ALTER TABLE projects ADD COLUMN tags TEXT NOT NULL DEFAULT '[]';

ALTER TABLE projects ADD COLUMN case_study TEXT NOT NULL DEFAULT '{}';

ALTER TABLE projects ADD COLUMN hero TEXT NOT NULL DEFAULT '';